version: '3'

services:
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo"
    hostname: mongo
    ports:
      - 27017:27017
  web:
    build: .
    command: 'npm start'
    container_name: web-server
    volumes:
      - ./src:/home/node/app/src
      -  ./nodemon.json:/home/node/app/nodemon.json
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo