version: '3'

services:
  redis:
    image: "redis:alpine"
  db:
    image: "mongo"
    ports:
      - 27017:27017
  web:
    build: .
    command: 'node ./src/index.ts'
    ports:
      - 3000:8000
    depends_on:
      - redis
      - db